import fs from "node:fs/promises"
import path from "node:path"
import { spawn } from "node:child_process"
import { fileURLToPath } from "node:url"
import { asNumber, ensureDir, mimeType, resolveInput, resolveOutput } from "../utils.mjs"

const rasterizeScript = fileURLToPath(new URL("../../adapters/image/rasterize_svg.py", import.meta.url))

const escapeXml = (value) => String(value ?? "")
  .replaceAll("&", "&amp;")
  .replaceAll("<", "&lt;")
  .replaceAll(">", "&gt;")
  .replaceAll('"', "&quot;")
  .replaceAll("'", "&apos;")

function attrs(value = {}) {
  return Object.entries(value)
    .filter(([, item]) => item !== undefined && item !== null)
    .map(([key, item]) => `${key}="${escapeXml(item)}"`)
    .join(" ")
}

function accessibility(options = {}, fallbackTitle = "Generated SVG") {
  if (options.decorative) return { root: 'role="presentation" aria-hidden="true"', metadata: "" }
  const title = options.title || fallbackTitle
  const description = options.description || "SVG artwork generated by Agent Toolkit"
  return {
    root: 'role="img" aria-labelledby="svg-title svg-desc"',
    metadata: `<title id="svg-title">${escapeXml(title)}</title><desc id="svg-desc">${escapeXml(description)}</desc>`,
  }
}

function elementToSvg(item) {
  const type = item.type || "circle"
  const common = { ...(item.attrs || {}) }
  if (item.className) common.class = item.className
  if (type === "text") return `<text ${attrs({ x: item.x ?? 0, y: item.y ?? 0, ...common })}>${escapeXml(item.text || "")}</text>`
  if (type === "path") return `<path ${attrs({ d: item.d || "", ...common })}/>`
  if (type === "line") return `<line ${attrs({ x1: item.x1 ?? 0, y1: item.y1 ?? 0, x2: item.x2 ?? 0, y2: item.y2 ?? 0, ...common })}/>`
  if (type === "rect") return `<rect ${attrs({ x: item.x ?? 0, y: item.y ?? 0, width: item.width ?? 10, height: item.height ?? 10, rx: item.rx, ...common })}/>`
  if (type === "ellipse") return `<ellipse ${attrs({ cx: item.cx ?? 0, cy: item.cy ?? 0, rx: item.rx ?? 10, ry: item.ry ?? 10, ...common })}/>`
  return `<circle ${attrs({ cx: item.cx ?? 0, cy: item.cy ?? 0, r: item.r ?? 10, ...common })}/>`
}

export async function createSvg(spec, output, options = {}) {
  const width = asNumber(spec.width, 800)
  const height = asNumber(spec.height, 600)
  const a11y = accessibility(spec, "Generated SVG scene")
  const background = spec.background ? `<rect width="100%" height="100%" fill="${escapeXml(spec.background)}"/>` : ""
  const body = (spec.elements || []).map(elementToSvg).join("\n  ")
  const svg = `<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" ${a11y.root}>${a11y.metadata}\n  ${background}\n  ${body}\n</svg>\n`
  const target = resolveOutput(output, options)
  await ensureDir(path.dirname(target))
  await fs.writeFile(target, svg, "utf8")
  return { svg: target, width, height }
}

export async function embedImage(image, output, options = {}) {
  const input = resolveInput(image)
  const data = (await fs.readFile(input)).toString("base64")
  const width = asNumber(options.width, 800)
  const height = asNumber(options.height, 600)
  const a11y = accessibility(options, "Embedded image")
  const svg = `<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" ${a11y.root}>${a11y.metadata}<image width="100%" height="100%" preserveAspectRatio="xMidYMid meet" href="data:${mimeType(input)};base64,${data}"/></svg>\n`
  const target = resolveOutput(output, options)
  await ensureDir(path.dirname(target))
  await fs.writeFile(target, svg, "utf8")
  return { svg: target, source: input, bytes: data.length }
}

export async function rasterizeSvg(input, output, options = {}) {
  const source = resolveInput(input)
  const target = resolveOutput(output, options)
  await ensureDir(path.dirname(target))
  const python = process.env.PYTHON_EXE || "python"
  const args = [rasterizeScript, "--input", source, "--output", target, "--width", String(options.width || 2048)]
  if (options.background) args.push("--background", options.background)
  return await new Promise((resolve, reject) => {
    const child = spawn(python, args, { cwd: path.dirname(rasterizeScript), windowsHide: true })
    let stdout = ""
    let stderr = ""
    child.stdout.on("data", (chunk) => { stdout += chunk })
    child.stderr.on("data", (chunk) => { stderr += chunk })
    child.on("error", (error) => reject(new Error(`Could not start CairoSVG: ${error.message}`)))
    child.on("close", (code) => {
      if (code !== 0) return reject(new Error(`CairoSVG exited with ${code}\n${stderr}`))
      try { resolve(JSON.parse(stdout.trim().split(/\r?\n/).at(-1))) } catch { resolve({ png: target, stdout: stdout.trim() }) }
    })
  })
}

const animationCss = {
  pulse: "0%,100%{opacity:.55;transform:scale(.96)}50%{opacity:1;transform:scale(1.04)}",
  float: "0%,100%{transform:translateY(0)}50%{transform:translateY(-18px)}",
  rotate: "from{transform:rotate(0deg)}to{transform:rotate(360deg)}"
}

export async function animateSvg(input, output, animation = "float", durationMs = 2400, options = {}) {
  const source = resolveInput(input)
  const svg = await fs.readFile(source, "utf8")
  const keyframes = animationCss[animation] || animationCss.float
  const duration = Math.max(100, asNumber(durationMs, 2400))
  const style = `<style>\n@keyframes agent-${animation}{${keyframes}}\n.agent-animated{transform-box:fill-box;transform-origin:center;animation:agent-${animation} ${duration}ms ease-in-out infinite;}\n</style>`
  const pattern = /<(path|rect|circle|ellipse|image|g|text)\b([^>]*)>/i
  const match = svg.match(pattern)
  let result = svg
  if (match) {
    const existing = match[2]
    const selfClosing = /\/\s*$/.test(existing)
    const clean = existing.replace(/\/\s*$/, "")
    const updated = clean.includes("class=")
      ? clean.replace(/class="([^"]*)"/, 'class="$1 agent-animated"')
      : `${clean} class="agent-animated"`
    const replacement = `<${match[1]}${updated}${selfClosing ? "/>" : ">"}`
    result = svg.replace(match[0], replacement)
  }
  result = result.replace(/<\/svg>\s*$/i, `${style}\n</svg>\n`)
  const target = resolveOutput(output, options)
  await ensureDir(path.dirname(target))
  await fs.writeFile(target, result, "utf8")
  return { svg: target, animation, durationMs: duration }
}

function random(seed) {
  let value = (seed >>> 0) || 1
  return () => {
    value = (1664525 * value + 1013904223) >>> 0
    return value / 4294967296
  }
}

export async function particles(output, options = {}) {
  const width = asNumber(options.width, 800)
  const height = asNumber(options.height, 600)
  const count = Math.min(1000, Math.max(1, Math.floor(asNumber(options.count, 40))))
  const next = random(asNumber(options.seed, 42))
  const circles = Array.from({ length: count }, (_, index) => {
    const x = Math.round(next() * width)
    const y = Math.round(next() * height)
    const r = (1 + next() * 4).toFixed(2)
    const delay = (next() * 3).toFixed(2)
    return `<circle cx="${x}" cy="${y}" r="${r}" fill="${options.color || "#7dd3fc"}" opacity="${(0.25 + next() * 0.75).toFixed(2)}"><animateTransform attributeName="transform" type="translate" values="0 0;0 -24;0 0" dur="${(2 + next() * 3).toFixed(2)}s" begin="-${delay}s" repeatCount="indefinite"/></circle>`
  }).join("\n  ")
  const a11y = accessibility(options, "Animated particles")
  const svg = `<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" ${a11y.root}>${a11y.metadata}<rect width="100%" height="100%" fill="${escapeXml(options.background || "#0f172a")}"/>\n  ${circles}\n</svg>\n`
  const target = resolveOutput(output, options)
  await ensureDir(path.dirname(target))
  await fs.writeFile(target, svg, "utf8")
  return { svg: target, count, seed: options.seed ?? 42 }
}

export async function validateSvg(input) {
  const source = resolveInput(input)
  const svg = await fs.readFile(source, "utf8")
  const errors = []
  const warnings = []
  if (!/<svg\b[^>]*xmlns=["']http:\/\/www\.w3\.org\/2000\/svg["']/i.test(svg)) errors.push("Missing SVG namespace")
  if (!/<svg\b[^>]*viewBox=["'][^"']+["']/i.test(svg)) warnings.push("Missing viewBox")
  if (!/<\/svg>\s*$/i.test(svg)) errors.push("Missing closing </svg>")
  if ((svg.match(/<svg\b/gi) || []).length !== 1) errors.push("Expected exactly one root svg element")
  if (/<script\b/i.test(svg)) warnings.push("SVG contains script content")
  if (/<image\b/i.test(svg) && !/href=["']data:/i.test(svg)) warnings.push("Image is not embedded and may require an external file")
  const root = svg.match(/<svg\b[^>]*>/i)?.[0] || ""
  const decorative = /aria-hidden=["']true["']/i.test(root) || /role=["']presentation["']/i.test(root)
  if (!decorative) {
    if (!/<title\b[^>]*>[\s\S]*?<\/title>/i.test(svg)) warnings.push("Missing accessible <title>")
    if (!/<desc\b[^>]*>[\s\S]*?<\/desc>/i.test(svg)) warnings.push("Missing accessible <desc>")
    if (!/role=["']img["']/i.test(root)) warnings.push("SVG root should declare role=\"img\"")
    if (!/aria-label(?:ledby)?=["'][^"']+["']/i.test(root)) warnings.push("SVG root should expose an accessible label")
  }
  return { valid: errors.length === 0, errors, warnings, file: source }
}

export async function previewSvg(input, output, options = {}) {
  const source = resolveInput(input)
  const svg = await fs.readFile(source, "utf8")
  const target = resolveOutput(output, options)
  await ensureDir(path.dirname(target))
  const html = `<!doctype html><html lang="en"><meta charset="utf-8"><title>SVG Preview</title><style>body{margin:0;background:#111827;color:#e5e7eb;font:14px system-ui}main{display:grid;place-items:center;min-height:100vh;padding:24px}section{max-width:1200px;width:100%}svg{display:block;max-width:100%;height:auto;background:#fff;box-shadow:0 20px 60px #0008}code{color:#93c5fd}</style><main><section><p>Preview: <code>${escapeXml(path.basename(source))}</code></p>${svg}</section></main></html>`
  await fs.writeFile(target, html, "utf8")
  return { html: target, source }
}
